// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewURL struct {
	Origin string `json:"origin"`
}

type URL struct {
	ID     string `json:"id"`
	Short  string `json:"short"`
	Origin string `json:"origin"`
}
